language: node_js
script:
    - "./interpreter.js examples/example_travis_config.json"
env:
    global:
        - SAUCE_USERNAME=zarkonnen
        - secure: "CqbgxeI6t40oWTuitRaYKZHAxJpY9CjTHZSkLeoA4HtRqRIbBQQsMpB3NvfUV/qukaJ8zgYsswvU4c+V1Dz26NC9tdCZV25nDLSHF1mEQ4GAkY1ALus4FGnkgcL+9UwRNX1hA4JtcYpQ+Rz8m5uPH/vBdGMyuNlFTkaV0/YTOdc="
